name: basic workflow
on:
  push: 
    branches: main
jobs:
  doing:
    name: do things
    runs-on: ububtu-latest
    steps:
      - name: basic workflow made
        run: echo "i built a workflow"
      - name: Error
        run: echo "i made an error"
      - name: exit
        run: Exit 1
        
