name: using defaults
on:
  push: 
    branches: feature/defaults
jobs:
  first-jobs:
    name: first job
    runs-on: ubuntu-latest
    steps:
      - name: make directory
        run: mkdir src
        shell: bash
      - name: use python
        run: import os; rint("I'm running python! Hissssss! " + os.getcwd());
        shell: python
        working-directory: src
      - name: use bash
        run: echo "I'm running hum-drum bash in $(pwd). Booo."
        shell: bash
        working-directory: src
      - name: use bash also
        run: echo "I'm running bash also, but elsewhere in $(pwd). Booo."
        shell: bash
  second-job:
    name: second job
    runs-on: ubuntu-latest
    steps:
      - name: create a directory
        run: mkdir src
        shell: bash
      - name: use bash
        run: echo "I'm running bash in $(pwd). So sad."
        shell: bash
        working-directory: src
