name: dependent jobs
on:
  push:
    branches: feature/dependent
jobs:
  first-job:
    name: first-job
    runs-on: ubuntu-latest
    steps:
      - name: dump job info
        env:
          CONTEXT_ITEM: ${{ toJson(job) }}
        run: echo "${CONTEXT_ITEM}"

  second-job:
    name: second job
    runs-on: ubuntu-latest
    steps:
      - name: dump job info
        env:
          CONTEXT_ITEM: ${{ toJson(job) }}
        run: echo "${CONTEXT_ITEM}"
